import type { ThemeConfig } from 'antd'
import { theme as antTheme } from 'antd'

export const appTheme: ThemeConfig = {
  cssVar: true,
  token: {
    colorWhite: '#ffffff',
    colorPrimary: '#5b5ce6',
    colorTextHeading: '#1b2252',
    colorTextBase: '#2b3155',
    colorText: '#5c648e',
    colorTextSecondary: '#7a82a8',
    colorLink: '#5b5ce6',
    colorLinkHover: '#7a6ef7',
    colorLinkActive: '#4c4dd1',
    colorIcon: '#5b5ce6',
    colorBgLayout: '#f3eefc',
    colorBgContainer: '#ffffff',
    colorBorder: '#dddff2',
    fontSizeHeading1: 30,
    fontSizeHeading2: 26,
    fontSizeHeading3: 22,
    fontSizeHeading4: 18,
    fontSizeHeading5: 16,
    lineHeightHeading1: 2,
    lineHeightHeading2: 2,
    lineHeightHeading3: 2,
    lineHeightHeading4: 2,
    lineHeightHeading5: 2,
    fontSize: 14,
    controlHeight: 40,
    sizeUnit: 4,
    sizeStep: 4,
    lineHeight: 1.5,
    borderRadius: 14,
    // fontFamily: 'Lora, Lato, Oswald, sans-serif',
    fontFamily:
      'ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";',
  },
  components: {
    Modal: {
      fontSizeHeading5: 24,
      // @ts-ignore - contentPadding is valid but not in type definitions
      contentPadding: 12,
      headerBg: 'transparent',
    },
    Checkbox: {},
    Layout: {
      headerBg: 'transparent',
      bodyBg: 'transparent',
    },
    Drawer: {
      colorBgElevated: '#ffffff', // bg body drawer
    },
    Menu: {
      itemBg: 'transparent',
      itemActiveBg: '#ecebff',
      itemHoverBg: '#f1f0ff',
      itemColor: '#5c648e',
      itemHoverColor: '#3b3fa6',
      itemSelectedColor: '#3b3fa6',
      itemSelectedBg: '#e8e7ff',
      itemBorderRadius: 12,
      // fontFamily: 'Lora, Lato, Oswald, sans-serif',
    },
    Button: {
      padding: 12,
      borderRadius: 12,
    },
    Input: {
      activeBorderColor: '#7a6ef7',
      hoverBorderColor: '#b9b5ff',
    },
    Select: {
      optionSelectedBg: '#ebeaff',
    },
  },
}

export const appDarkTheme: ThemeConfig = {
  cssVar: true,
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorWhite: '#eceeff',
    colorPrimary: '#8b6ef7',
    colorTextHeading: '#eceeff',
    colorTextBase: '#e0e2ff',
    colorText: '#9da3cc',
    colorTextSecondary: '#6d75a5',
    colorLink: '#9d87f8',
    colorLinkHover: '#b8a8ff',
    colorLinkActive: '#7a60f3',
    colorIcon: '#9d87f8',
    colorBgLayout: '#0e1130',
    colorBgContainer: '#171b45',
    colorBgElevated: '#1c2152',
    colorBorder: 'rgba(130, 115, 255, 0.14)',
    colorFill: 'rgba(130, 115, 255, 0.08)',
    colorFillSecondary: 'rgba(130, 115, 255, 0.05)',
    colorFillTertiary: 'rgba(130, 115, 255, 0.03)',
    fontSizeHeading1: 30,
    fontSizeHeading2: 26,
    fontSizeHeading3: 22,
    fontSizeHeading4: 18,
    fontSizeHeading5: 16,
    lineHeightHeading1: 2,
    lineHeightHeading2: 2,
    lineHeightHeading3: 2,
    lineHeightHeading4: 2,
    lineHeightHeading5: 2,
    fontSize: 14,
    controlHeight: 40,
    sizeUnit: 4,
    sizeStep: 4,
    lineHeight: 1.5,
    borderRadius: 14,
    // fontFamily: 'Lora, Lato, Oswald, sans-serif',
    fontFamily:
      'ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";',
  },
  components: {
    Modal: {
      fontSizeHeading5: 24,
      // @ts-ignore
      contentPadding: 12,
      headerBg: 'transparent',
      contentBg: '#111332',
    },
    Checkbox: {},
    Layout: {
      headerBg: 'transparent',
      bodyBg: 'transparent',
      siderBg: '#0b0e2a',
    },
    Drawer: {
      colorBgElevated: '#191d49',
    },
    Menu: {
      itemBg: 'transparent',
      itemActiveBg: 'rgba(130, 110, 255, 0.15)',
      itemHoverBg: 'rgba(130, 110, 255, 0.08)',
      itemColor: '#8890b8',
      itemHoverColor: '#c8ccff',
      itemSelectedColor: '#c5c9ff',
      itemSelectedBg: 'rgba(130, 110, 255, 0.18)',
      itemBorderRadius: 12,
      // fontFamily: 'Lora, Lato, Oswald, sans-serif',
    },
    Button: {
      padding: 12,
      borderRadius: 12,
      defaultBg: 'rgba(130, 110, 255, 0.08)',
      defaultBorderColor: 'rgba(130, 110, 255, 0.22)',
      defaultColor: '#c5c9ff',
    },
    Input: {
      activeBorderColor: '#8b6ef7',
      hoverBorderColor: 'rgba(139, 110, 247, 0.45)',
      colorBgContainer: 'rgba(14, 16, 53, 0.8)',
      colorText: '#c8caee',
    },
    Select: {
      optionSelectedBg: 'rgba(130, 110, 255, 0.18)',
      colorBgContainer: 'rgba(14, 16, 53, 0.8)',
    },
    Dropdown: {
      colorBgElevated: '#1b2050',
    },
    AutoComplete: {
      colorBgContainer: 'rgba(23, 27, 69, 0.95)',
    },
    Skeleton: {
      gradientFromColor: 'rgba(130, 115, 255, 0.06)',
      gradientToColor: 'rgba(130, 115, 255, 0.12)',
    },
  },
}
